FROM node:8-alpine

ENV NODE_ENV development

RUN mkdir -p /opt/app/fake-user-api

ADD package.json package-lock.json /opt/app/fake-user-api/

WORKDIR /opt/app/fake-user-api

RUN npm install

CMD ["npm", "start"]
